name: 'csv-contribution-action'
description: 'Checks contributions to CSV files'
inputs:
  file-content:
    description: 'File content'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'